# Generated by Django 5.2.7 on 2025-10-04 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('init_amount', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('currency', models.CharField(choices=[('NTD', 'New Taiwan Dollar'), ('USD', 'United States Dollar'), ('EUR', 'Euro'), ('GBP', 'Great British Pound')], default='NTD', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
