# Generated by Django 5.2.7 on 2025-10-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='init_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
