# Generated by Django 5.2.7 on 2025-10-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_init_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cur_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('NT$', 'New Taiwan Dollar'), ('US$', 'United States Dollar'), ('€', 'Euro'), ('£', 'Great British Pound')], default='NT$', max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='UserAccount', max_length=30),
        ),
    ]
