# Generated by Django 5.2.7 on 2025-10-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cur_amount',
        ),
    ]
