# Generated by Django 5.2.7 on 2025-10-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_cur_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cur_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
