# Generated by Django 5.2.7 on 2025-10-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_cur_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('NT$', 'NTD'), ('US$', 'USD'), ('€', 'EUR'), ('£', 'GBP')], default='NT$', max_length=30),
        ),
    ]
