# Generated by Django 5.2.7 on 2025-11-10 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'created_at'], name='accounts_ac_user_id_452791_idx'),
        ),
    ]
