# Generated by Django 5.2.7 on 2025-10-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('Restaurants', 'Restaurants'), ('Transportation', 'Transportation'), ('Groceries', 'Groceries'), ('Shopping', 'Shopping'), ('Housing', 'Housing'), ('Life & Entertainment', 'Life & Entertainment'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
