# Generated by Django 5.2.7 on 2025-10-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_category_record_created_at_record_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('Restaurants', 'Restaurants'), ('Transportation', 'Transportation'), ('Groceries', 'Groceries'), ('Shopping', 'Shopping'), ('Housing', 'Housing'), ('Life & Entertainment', 'Life & Entertainment'), ('Others', 'Others')], max_length=20),
        ),
    ]
