# Generated by Django 5.2.7 on 2025-10-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_record_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'permissions': [('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can remove a task by setting its status as closed')]},
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('Restaurants', 'Restaurants'), ('Transportation', 'Transportation'), ('Groceries', 'Groceries'), ('Shopping', 'Shopping'), ('Housing', 'Housing'), ('Life & Entertainment', 'Life & Entertainment'), ('Income', 'Income'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=20),
        ),
    ]
