# Generated by Django 5.2.7 on 2025-10-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_record_options_alter_record_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={},
        ),
    ]
