# Generated by Django 5.2.7 on 2025-10-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_record_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'permissions': [('can_create_record', 'Can create record'), ('can_view_records', 'Can view records')]},
        ),
    ]
