# Generated by Django 5.2.7 on 2025-11-10 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_currency'),
        ('records', '0006_alter_record_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['user', 'created_at'], name='records_rec_user_id_cf4b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['user', 'account', 'category', 'created_at'], name='records_rec_user_id_9b2096_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['user', 'account', 'created_at'], name='records_rec_user_id_949118_idx'),
        ),
    ]
