# Generated by Django 5.2.7 on 2025-11-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_record_records_rec_user_id_cf4b3b_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={},
        ),
    ]
