# Generated by Django 5.2.7 on 2025-11-10 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_accounts_ac_user_id_452791_idx'),
        ('records', '0008_alter_record_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_account', to='accounts.account'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['user', 'category', 'created_at'], name='records_rec_user_id_424fd9_idx'),
        ),
    ]
