# Generated by Django 5.2.7 on 2025-11-10 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_accounts_ac_user_id_452791_idx'),
        ('records', '0009_alter_record_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_record', to='accounts.account'),
        ),
    ]
