# Generated by Django 5.2.7 on 2025-11-10 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_accounts_ac_user_id_452791_idx'),
        ('records', '0010_alter_record_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='accounts.account'),
        ),
    ]
